### ISSUE TITLE
Language & Framework section looks blank

### ISSUE THREAD

**Issue by cringer** [CodePier/CodePier-Issues#17]
### Browser and Version
Chrome 55.0.2883

### Steps to reproduce
1. Create new site
2. Start to fill out repository information and provider
3. Click on the drop down for Language & Framework

### What is Expected?
Should see the options in the select list

### What is actually happening?
The select list appears blank.  You can hover over the blank spots and once the background color comes in you can read it.  This is because the select box text color is white.

![codepier](https://user-images.githubusercontent.com/835448/30005101-eec4fcdc-908f-11e7-8b63-910e84375689.png)

![codepier2](https://user-images.githubusercontent.com/835448/30005105-1120e5d4-9090-11e7-8a34-7ba299b7eebb.png)

**Comment by dmfj** [comment]
@cringer What OS / browser are you running?

**Comment by lukepolo** [comment]
He stated it in the issue at the top 😎

**Comment by cringer** [comment]
Well my OS is Windows 10 though I don't think that's relevant for browser rendering.

I primarily use Chrome Canary with standard Chrome as a fallback.  Also have Mozilla Firefox.  All display the same symptoms.

**Comment by dmfj** [comment]
@cringer Thanks for the report! This issue was indeed able to reproduce this issue under a Windows-based environment. We work primarily under macOS, so these issues can be sometimes hard to spot.

![Issue](https://user-images.githubusercontent.com/13137236/30036707-b0e7a460-9183-11e7-997c-6df9536edfd0.png)

I'm assigning @jfalotico here to take a look...

**Comment by jfalotico** [comment]
Made and update for this. Will be fixed in the next release
